@startuml
' Diperbarui pada: 2026-06-23 04:04:05
skinparam style strictuml
left to right direction

  class KasirGudangApp #FFCCCC {
    # _atur_hak_akses
    # _buat_layout_gui
    + SERVER_URL
    + after
    + aktifkan_mode_darurat
    + alur_cepat_input_barang
    + area_keranjang
    + berat_stabil_sebelumnya
    + bind
    + btn_darurat
    + btn_tambah_nol
    + cek_koneksi_server_loop
    + combo_metode
    + config
    + controller
    + current_barang
    + current_page
    + edit_jumlah_item_berdasarkan_nomor
    + geometry
    + hapus_item_terakhir
    + hitung_kembalian_otomatis
    + id_kasir
    + input_bayar
    + input_berat
    + input_kode
    + is_running
    + is_timbangan_active
    + jalankan_render_dashboard_utama
    + keranjang_transaksi
    + konten_frame
    + last_sync_time
    + lbl_kembalian
    + lbl_nominal_bayar
    + lbl_status_server
    + lbl_total
    + login_induk
    + menu_file
    + metode_pembayaran_aktif
    + mode_bypass_aktif
    + nama
    + nilai_timbangan_terakhir
    + peran
    + proses_tambah_ke_keranjang
    + protocol
    + resizable
    + set_server_status
    + simpan_ke_server
    + sudah_masuk_keranjang
    + tambah_nol_tiga_kali
    + thread_check
    + thread_timbangan
    + timbangan_tersambung
    + title
    + total_bayar
    + ubah_mode_tampilan_menu
    + update_dari_thread_timbangan
    + update_id
    + update_tampilan_tabel
    + user_saat_ini
    + validasi_supervisor
    + waktu_mulai_stabil
    + winfo_exists
    --
    + jalankan_render_dashboard_utama [CC: 1]
    + bersihkan_konten [CC: 2] 💤 [DEAD]
    + cek_koneksi_server_loop [CC: 9] 💤 [DEAD]
    + set_server_status [CC: 4] 💤 [DEAD]
    + update_dari_thread_timbangan [CC: 19]
    + alur_cepat_input_barang [CC: 8]
    + update_tampilan_tabel [CC: 2]
    + format_dan_hitung_realtime [CC: 5]
    + hitung_kembalian_otomatis [CC: 4]
    + validasi_supervisor [CC: 8]
    + aktifkan_mode_darurat [CC: 3]
    + simpan_ke_server [CC: 21]
  }
  class MockRes #FFFFFF {
    + status_code
    --
    ' (Tidak ada fungsi)
  }
package "views" {
  class AboutView #FFFFFF {
    + btn_close
    + btn_email
    + btn_web
    + controller
    + destroy
    + geometry
    + grab_set
    + grid_columnconfigure
    + lbl_app_name
    + lbl_author_info
    + lbl_author_title
    + lbl_contact_title
    + lbl_desc
    + lbl_version
    + resizable
    + separator
    + title
    + transient
    + winfo_screenheight
    + winfo_screenwidth
    --
    ' (Tidak ada fungsi)
  }
  note top of AboutView : Modul Tampilan About dalam bentuk Jendela Terpisah (Pop-up Window) Menampilkan informasi software, pengarang, dan dukungan kontak.
  class LayoutGuiKasir #FFCCCC {
    # _navigasi_combo
    # _pilih_lewat_enter
    # _pilih_metode_pembayaran
    + aktifkan_mode_darurat
    + area_keranjang
    + btn_darurat
    + btn_edit_jumlah
    + btn_hapus_nomor_item
    + btn_hapus_terakhir
    + btn_kosongkan_keranjang
    + btn_simpan
    + btn_tambah
    + btn_tambah_nol
    + combo_metode
    + dropdown_skala
    + edit_jumlah_item_berdasarkan_nomor
    + format_dan_hitung_realtime
    + frame_input
    + frame_kembalian
    + frame_tabel
    + frame_total
    + hapus_item_berdasarkan_nomor
    + hapus_item_terakhir
    + hitung_kembalian_otomatis
    + input_bayar
    + input_berat
    + input_kode
    + kosongkan_keranjang
    + lbl_kembalian
    + lbl_nominal_bayar
    + lbl_petugas
    + lbl_total
    + metode_pembayaran_aktif
    + nama
    + peran
    + proses_tambah_ke_keranjang
    + simpan_ke_server
    + skala_options
    + switch_tema
    + tambah_nol_tiga_kali
    + ubah_skala_fix
    --
    # _buat_layout_gui [CC: 1]
    # _navigasi_combo [CC: 5]
    # _pilih_lewat_enter [CC: 2]
    + ubah_mode_tampilan [CC: 2] 💤 [DEAD]
    + ubah_mode_tampilan_menu [CC: 4] 💤 [DEAD]
    + ubah_skala_fix [CC: 1] 💤 [DEAD]
    # _atur_hak_akses [CC: 2]
    # _pilih_metode_pembayaran [CC: 2]
    + tambah_nol_tiga_kaliA [CC: 1] 💤 [DEAD]
    + tambah_nol_tiga_kali [CC: 5]
  }
  class AutoCRUDFrame #FFCCCC {
    # _deteksi_struktur_tabel
    + btn_next
    + btn_prev
    + buat_footer_pagination_ui
    + buat_header_ui
    + buat_tabel_ui
    + buka_form_dialog
    + canvas
    + canvas_window
    + conn
    + current_page
    + cursor
    + db_params
    + destroy
    + ekspor_ke_excel
    + footer_frame
    + grid_columnconfigure
    + grid_forget
    + grid_rowconfigure
    + halaman_berikutnya
    + halaman_sebelumnya
    + hapus_data_konfirmasi
    + hsb
    + hubungkan_ke_postgres
    + kembali_ke_home
    + kolom
    + lbl_judul
    + lbl_page_info
    + main_container
    + master
    + pastikan_koneksi_aktif
    + primary_key
    + refresh_data
    + reset_dan_refresh
    + role
    + rows_per_page
    + scroll_frame
    + search_entry
    + table_name
    + total_pages
    + vsb
    --
    + hubungkan_ke_postgres [CC: 4]
    + pastikan_koneksi_aktif [CC: 5]
    # _deteksi_struktur_tabel [CC: 3]
    + buat_header_ui [CC: 2]
    + kembali_ke_home [CC: 3] 💤 [DEAD]
    + buat_tabel_ui [CC: 1]
    + buat_footer_pagination_ui [CC: 1]
    + reset_dan_refresh [CC: 1]
    + halaman_sebelumnya [CC: 2] 💤 [DEAD]
    + halaman_berikutnya [CC: 2] 💤 [DEAD]
    + refresh_data [CC: 13]
    + buka_form_dialog [CC: 10]
    + hapus_data_konfirmasi [CC: 4]
    + ekspor_ke_excel [CC: 7] 💤 [DEAD]
  }
  note top of AutoCRUDFrame : [BAGIAN 1] Framework Komponen CustomTkinter Otomatis untuk CRUD & Ekspor Tabel PostgreSQL. Dioptimalkan untuk Performa Tinggi, Skalabilitas Data, dan Hak Akses Terbuka.
  class PasswordView #FFFFFF {
    + btn_submit
    + controller
    + eksekusi_submit
    + entry_confirm_pwd
    + entry_new_pwd
    + entry_old_pwd
    + entry_username
    + geometry
    + grab_set
    + grid_columnconfigure
    + label_title
    + resizable
    + title
    + transient
    + winfo_screenheight
    + winfo_screenwidth
    --
    + eksekusi_submit [CC: 1]
  }
  class BypassDialog #FFFFFF {
    + btn_cancel
    + btn_frame
    + btn_ok
    + destroy
    + geometry
    + grab_set
    + label
    + on_cancel
    + on_submit
    + password_entry
    + protocol
    + resizable
    + result
    + title
    + transient
    + username_entry
    + wait_visibility
    + wait_window
    + winfo_screenheight
    + winfo_screenwidth
    --
    + on_submit [CC: 3]
    + on_cancel [CC: 1] 💤 [DEAD]
  }
  class AutoCRUDFrame #FFCCCC {
    # _deteksi_struktur_tabel
    + buat_header_ui
    + buat_tabel_ui
    + buka_form_dialog
    + canvas
    + canvas_window
    + conn
    + current_page
    + cursor
    + db_name
    + destroy
    + ekspor_ke_excel
    + grid_columnconfigure
    + grid_forget
    + grid_rowconfigure
    + hapus_data
    + hsb
    + kembali_ke_home
    + kolom
    + lbl_judul
    + main_container
    + master
    + next_page
    + pack_forget
    + pagination_frame
    + prev_page
    + primary_key
    + refresh_data
    + render_pagination_controls
    + role
    + rows_per_page
    + scroll_frame
    + search_entry
    + table_name
    + total_pages
    + vsb
    --
    # _deteksi_struktur_tabel [CC: 1]
    + buat_header_ui [CC: 2]
    + kembali_ke_home [CC: 3] 💤 [DEAD]
    + buat_tabel_ui [CC: 1]
    + refresh_data [CC: 7]
    + buka_form_dialog [CC: 2]
    + hapus_data [CC: 3]
    + ekspor_ke_excel [CC: 6] 💤 [DEAD]
    + render_pagination_controls [CC: 2]
    + next_page [CC: 1] 💤 [DEAD]
    + prev_page [CC: 1] 💤 [DEAD]
  }
  note top of AutoCRUDFrame : Framework Komponen CustomTkinter Otomatis untuk CRUD & Ekspor Tabel SQLite Sudah dilengkapi Fitur Keamanan Hak Akses (Role-Based Access Control)
  class DynamicFormWindow #FFFFFF {
    + buat_form_dinamis
    + daftar_kolom
    + data_lama
    + destroy
    + entries
    + geometry
    + grab_set
    + grid_columnconfigure
    + grid_rowconfigure
    + mode
    + parent_frame
    + proses_simpan
    + resizable
    + title
    --
    + buat_form_dinamis [CC: 5]
    + proses_simpan [CC: 6] 💤 [DEAD]
  }
  note top of DynamicFormWindow : Jendela Form Input yang Membuat Dirinya Sendiri Secara Otomatis (Versi Perbaikan Scroll)
  class PrinterView #FFFFFF {
    + baca_printer_dari_config
    + btn_simpan
    + combo_printer
    + destroy
    + geometry
    + grab_set
    + label
    + list_printer
    + resizable
    + simpan_printer
    + title
    + transient
    + winfo_screenheight
    + winfo_screenwidth
    --
    + baca_printer_dari_config [CC: 4]
    + simpan_printer [CC: 6] 💤 [DEAD]
  }
  class StokBarangView #FFFFFF {
    + buat_database_jika_belum_ada
    + current_role
    + grid_columnconfigure
    + grid_rowconfigure
    + panel_stok_otomatis
    --
    ' (Tidak ada fungsi)
  }
  class LoginWindow #FFFFFF {
    + btn_login
    + callback_sukses
    + eksekusi_masuk
    + geometry
    + input_pass
    + input_user
    + lbl_footer
    + lbl_judul
    + proses_login
    + resizable
    + title
    + token_aktif
    + username_aktif
    + winfo_screenheight
    + winfo_screenwidth
    + withdraw
    --
    + proses_login [CC: 13]
    + eksekusi_masuk [CC: 1]
  }
}

package "models" {
  class KonfigurasiTimbangan #FFFFFF {
    + is_timbangan_active
    + port_klien
    --
    + baca_konfigurasi_timbangan [CC: 4] 💤 [DEAD]
  }
}

package "controllers" {
  class Keranjang #FFCCCC {
    + cari_barang
    + hitung_kembalian_otomatis
    + input_berat
    + input_kode
    + is_timbangan_active
    + keranjang_transaksi
    + total_bayar
    + update_tampilan_tabel
    + validasi_supervisor
    --
    + cari_barang [CC: 1]
    + proses_tambah_ke_keranjang [CC: 12]
    + hapus_item_terakhir [CC: 6]
    + hapus_item_berdasarkan_nomor [CC: 7] 💤 [DEAD]
    + kosongkan_keranjang [CC: 5] 💤 [DEAD]
    + edit_jumlah_item_berdasarkan_nomor [CC: 11]
  }
  class PasswordController #FFFFFF {
    + server_url
    --
    + handle_change_password [CC: 10]
  }
  class TimbanganThread #FFFFFF {
    # _read_serial
    + baudrate
    + data_queue
    + port
    + running
    + thread
    --
    + start [CC: 1]
    + stop [CC: 1]
    + is_alive [CC: 2]
    # _read_serial [CC: 16]
  }
}

LayoutGuiKasir <|-- KasirGudangApp
Keranjang <|-- KasirGudangApp
@enduml